security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # Le provider utilise l'entité User et l'email comme identifiant
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Désactive la sécurité sur les assets et le profiler Symfony
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login       # route affichant le formulaire de login
                check_path: login       # route traitant les données du formulaire
                default_target_path: app_redirect_after_login  # route après connexion réussie
            logout:
                path: logout            # route pour déconnexion

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Contrôle d'accès aux URLs en fonction des rôles
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4        # Lowest possible value for bcrypt
                time_cost: 3   # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
